server:
    port: 8082
spring:
  application:
    name: sp-medical-group
  flyway:
    enabled: true
    locations: classpath:db/migration
  r2dbc:
      url: r2dbc:pool:sqlserver://localhost:1433
      database: DB_SPMG
      username: USER
      password: Senha123!
  profiles:
    active: test
logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG