server:
    port: 8082
spring:
  application:
    name: sp-medical-group
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=DB_SPMG;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  profiles:
    active: test

